### PR TITLE
File properties rework3

### PR DESCRIPTION
**Pull request by justinkrojos**

### CODE REVIEW

**Comment by franc-hoon** [comment]
the hashtag section seems a bit big no?

**Comment by justinkrojos** [comment]
To Francis, 
Thank you for the reply, you are absolutely correct! My understanding was that as I did not know how much space the tags section requires, I could give it the remaining space and alter the relevant proportions after.
Yours truly, 
Justin

Edit: please keep your comments professional.

**Comment by franc-hoon** [comment]
> To Francis,
> Thank you for the reply, you are absolutely correct! My understanding was that as I did not know how much space the tags section requires, I could give it the remaining space and alter the relevant proportions after.
> Yours truly,
> Justin
> 
> Edit: please keep your comments professional.

Justin, there is a time and place to be professional. We are all friends here so there is no need to talk in such manner. As for the issue, I think it would be fine to hard code the tag section to allow maybe a line or two of tags and fill the rest with the chat and task board. Also i think it'd be nicer to keep all the corners sharp. And line up the X icon with the right margin thank you :)

**Comment by justinkrojos** [comment]
Alright, I reckon we leave it as it is for now (and merge it). After Steven completes his tags, I will allocate the space accordingly and finalise the file-properties.
Is that algood?

**Review by franc-hoon — APPROVED** [review]
Feel free to merge 👍

**Pull request merged**
